services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 8000:8000
  api:
    depends_on:
      postgres:         
        condition: service_started
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    networks:
      - backend
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://tracker:tracker@postgres:5432/performance_tracker?schema=public
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: tracker
      POSTGRES_DB: performance_tracker

volumes:
  postgres-data:

networks:
  backend:
    name: backend