name: "Docker Compose"

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build dockerized application
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run docker-compose
        uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--build"
          down-flags: "--volumes"