name: "Integration tests"

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run docker-compose
        run: docker compose up -d --build
      
      - name: "Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Install npm@latest"
        run: npm i -g npm@latest

      - name: "Install dependencies"
        uses: bahmutov/npm-install@v1

      - name: "Create api .env file"
        run: cp -n ./apps/api/.env.example ./apps/api/.env

      - name: "Execute integration tests"
        run: npm run int-test

      - name: Run docker-compose
        run: docker compose down --volumes